# organization name, it's used to get github repo url, also in page title
name: eggjs

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       egg
description: A web framework's framework for Node.js
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - egg
 - egg-core
 - egg-logger
 - egg-cluster
 - egg-cookies
 - egg-utils
 - egg-bin
 - egg-mock
 - egg-init
 - egg-ci
 - egg-onerror
 - egg-alinode
 - egg-schedule
 - egg-rest
 - egg-logrotator
 - egg-dingtalk
 - egg-view-nunjucks
 - egg-multipart
 - egg-i18n
 - egg-userservice
 - egg-validate
 - egg-cors
 - egg-security
 - egg-development
 - egg-watcher
 - egg-userrole
 - egg-static
 - egg-session

# list of maintainers, this won't be sorted
maintainers:
 - name:    Feng Yuan
   github:  fengmk2   # github account, required: we link to it
   npm:     fengmk2   # npm account, required to determine lead maintainer
   twitter: fengmk2   # twitter account, optional
   gittip:  fengmk2   # gittub badge, optional
   email:   fengmk2@gmail.com

 - name:    Haoliang Gao
   github:  popomore
   npm:     popomore
   twitter: popomore
   gittip:  popomore
   email:   sakura9515@gmail.com

 - name:    TZ | 天猪
   github:  atian25
   npm:     atian25
   twitter: atian25
   gittip:  atian25
   email:   atian25@qq.com

 - name:    jtyjty99999
   github:  jtyjty99999
   npm:     jtyjty99999
   twitter: jtyjty99999
   gittip:  jtyjty99999
   email:   jtyjty99999@126.com

 - name:    Yiyu He
   github:  dead-horse
   npm:     dead-horse
   twitter: dead-horse
   gittip:  dead-horse
   email:   heyiyu.deadhorse@gmail.com

 - name:    GaoXiaochen
   github:  gxcsoccer
   npm:     gxcsoccer
   twitter: gxcsoccer
   gittip:  gxcsoccer
   email:   gxcsoccer@126.com

 - name:    tangyao
   github:  coolme200
   npm:     coolme200
   twitter: coolme200
   gittip:  coolme200
   email:   2001-wms@163.com

 - name:    Matt Ma
   github:  mattma
   npm:     mattma
   twitter: bigmabig
   gittip:  mattma
   email:   matt@mattmadesign.com

 - name:    Deng Ruoqi
   github:  luckydrq
   npm:     luckydrq
   twitter: luckydrq
   gittip:  luckydrq
   email:   drqzju@gmail.com

 - name:    Shawn
   github:  shaoshuai0102
   npm:     shaoshuai0102
   twitter: shaoshuai0102
   gittip:  shaoshuai0102
   email:   shaoshuai0102@gmail.com

 - name:    hui
   github:  leoner
   npm:     leoner
   twitter: leoner
   gittip:  leoner
   email:   kangpangpang@gmail.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
